### ISSUE TITLE
Failed to load, cannot find module redux

### ISSUE THREAD

**Issue by endorama** [timothy-s-dev/inkdrop-outliner-plugin#4]
Hello, while trying to install this plugin on InkDrop 5.1.1 I get this error, that prevents the plugin from working as expected.

<details>
<summary>Details</summary>

```
/snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/node_modules/debug/src/common.js:114 app:error Notification: +0ms Failed to load the outliner package Object detail: "Cannot find module 'redux'
Require stack:
- /.../snap/inkdrop/35/.config/inkdrop/packages/outliner/lib/outliner-container.js
- /.../snap/inkdrop/35/.config/inkdrop/packages/outliner/lib/outliner.js
- /snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/index.html"dismissable: truepackageName: "outliner"stack: "Error: Cannot find module 'redux'
Require stack:
- /.../snap/inkdrop/35/.config/inkdrop/packages/outliner/lib/outliner-container.js
- /.../snap/inkdrop/35/.config/inkdrop/packages/outliner/lib/outliner.js
- /snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/renderer_init.js:930:16)
    at Module.e.require (file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:4:122361)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (outliner-container.js:5:1)
    at Object.<anonymous> (/.../snap/inkdrop/35/.config/inkdrop/packages/outliner/lib/outliner-container.js:102:3)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.value [as .js] (file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:4:104608)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.e.require (file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:4:122618)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (outliner.js:2:1)
    at Object.<anonymous> (outliner.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.value [as .js] (file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:4:104608)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.e.require (file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:4:122618)
    at require (internal/modules/cjs/helpers.js:68:18)
    at t.default.requireMainModule (file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:1:30450)
    at file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:1:16945
    at t.default.measure (file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:1:15788)
    at t.default.load (file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:1:16518)
    at e.exports.loadPackage (file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:4:515125)
    at e.exports.loadPackages (file:///snap/inkdrop/35/usr/lib/inkdrop/resources/app.asar/browser-main.js:4:513904)"__proto__: Object
```

</details>

**Comment by alter777** [comment]
Same problem here with InkDrop version 5.2.0 could not install the plugin. See screenshot below.Thanks.

<img width="1280" alt="Screenshot 2021-01-05 at 17 06 43" src="https://user-images.githubusercontent.com/16539805/103678619-a6074c80-4f7b-11eb-8497-537dcf0b2df7.png">
